'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("divANS_gui.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GUI software by: Moisés Cardona.
        '''</summary>
        Friend ReadOnly Property About() As String
            Get
                Return ResourceManager.GetString("About", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Programa GUI por: Moisés Cardona.
        '''</summary>
        Friend ReadOnly Property AboutSpanish() As String
            Get
                Return ResourceManager.GetString("AboutSpanish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Action.
        '''</summary>
        Friend ReadOnly Property Action() As String
            Get
                Return ResourceManager.GetString("Action", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Acción.
        '''</summary>
        Friend ReadOnly Property ActionSpanish() As String
            Get
                Return ResourceManager.GetString("ActionSpanish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Browse File.
        '''</summary>
        Friend ReadOnly Property BrowseFileButton() As String
            Get
                Return ResourceManager.GetString("BrowseFileButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Buscar Archivo.
        '''</summary>
        Friend ReadOnly Property BrowseFileButtonSpanish() As String
            Get
                Return ResourceManager.GetString("BrowseFileButtonSpanish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Browse Folder.
        '''</summary>
        Friend ReadOnly Property BrowseFolderButton() As String
            Get
                Return ResourceManager.GetString("BrowseFolderButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Buscar Carpeta.
        '''</summary>
        Friend ReadOnly Property BrowseFolderButtonSpanish() As String
            Get
                Return ResourceManager.GetString("BrowseFolderButtonSpanish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Browse.
        '''</summary>
        Friend ReadOnly Property BrowseOutputButton() As String
            Get
                Return ResourceManager.GetString("BrowseOutputButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Buscar.
        '''</summary>
        Friend ReadOnly Property BrowseOutputButtonSpanish() As String
            Get
                Return ResourceManager.GetString("BrowseOutputButtonSpanish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compressed files will be saved at the input folder.
        '''</summary>
        Friend ReadOnly Property CompressFolderSelectedMessage() As String
            Get
                Return ResourceManager.GetString("CompressFolderSelectedMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Archivos comprimidos serán guardados en su carpeta original.
        '''</summary>
        Friend ReadOnly Property CompressFolderSelectedMessageSpanish() As String
            Get
                Return ResourceManager.GetString("CompressFolderSelectedMessageSpanish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compressing....
        '''</summary>
        Friend ReadOnly Property Compressing() As String
            Get
                Return ResourceManager.GetString("Compressing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comprimiendo....
        '''</summary>
        Friend ReadOnly Property CompressingSpanish() As String
            Get
                Return ResourceManager.GetString("CompressingSpanish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Step 1: Browse for a file or folder to compress:.
        '''</summary>
        Friend ReadOnly Property CompressInputMessage() As String
            Get
                Return ResourceManager.GetString("CompressInputMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paso 1: Busque un archivo o carpeta para comprimir:.
        '''</summary>
        Friend ReadOnly Property CompressInputMessageSpanish() As String
            Get
                Return ResourceManager.GetString("CompressInputMessageSpanish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Step 2: Browse for a location to save the compressed file:.
        '''</summary>
        Friend ReadOnly Property CompressOutputMessage() As String
            Get
                Return ResourceManager.GetString("CompressOutputMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paso 2: Busque un lugar para guardar el archivo comprimido:.
        '''</summary>
        Friend ReadOnly Property CompressOutputMessageSpanish() As String
            Get
                Return ResourceManager.GetString("CompressOutputMessageSpanish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compress.
        '''</summary>
        Friend ReadOnly Property CompressRButton() As String
            Get
                Return ResourceManager.GetString("CompressRButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comprimir.
        '''</summary>
        Friend ReadOnly Property CompressRButtonSpanish() As String
            Get
                Return ResourceManager.GetString("CompressRButtonSpanish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Extracted files will be saved at the input folder.
        '''</summary>
        Friend ReadOnly Property ExtractFolderSelectedMessage() As String
            Get
                Return ResourceManager.GetString("ExtractFolderSelectedMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Archivos descomprimidos serán guardados en su carpeta original.
        '''</summary>
        Friend ReadOnly Property ExtractFolderSelectedMessageSpanish() As String
            Get
                Return ResourceManager.GetString("ExtractFolderSelectedMessageSpanish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Extracting....
        '''</summary>
        Friend ReadOnly Property Extracting() As String
            Get
                Return ResourceManager.GetString("Extracting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Descomprimiendo....
        '''</summary>
        Friend ReadOnly Property ExtractingSpanish() As String
            Get
                Return ResourceManager.GetString("ExtractingSpanish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Step 1: Browse for a compressed file to extract:.
        '''</summary>
        Friend ReadOnly Property ExtractInputMessage() As String
            Get
                Return ResourceManager.GetString("ExtractInputMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paso 1: Busque un archivo o carpeta para descomprimir:.
        '''</summary>
        Friend ReadOnly Property ExtractInputMessageSpanish() As String
            Get
                Return ResourceManager.GetString("ExtractInputMessageSpanish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Step 2: Browse for a location to save the extracted file:.
        '''</summary>
        Friend ReadOnly Property ExtractOutputMessage() As String
            Get
                Return ResourceManager.GetString("ExtractOutputMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paso 2: Busque un lugar para guardar el archivo descomprimido:.
        '''</summary>
        Friend ReadOnly Property ExtractOutputMessageSpanish() As String
            Get
                Return ResourceManager.GetString("ExtractOutputMessageSpanish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Extract.
        '''</summary>
        Friend ReadOnly Property ExtractRButton() As String
            Get
                Return ResourceManager.GetString("ExtractRButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Extraer.
        '''</summary>
        Friend ReadOnly Property ExtractRButtonSpanish() As String
            Get
                Return ResourceManager.GetString("ExtractRButtonSpanish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Finished!.
        '''</summary>
        Friend ReadOnly Property Finished() As String
            Get
                Return ResourceManager.GetString("Finished", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¡Finalizado!.
        '''</summary>
        Friend ReadOnly Property FinishedSpanish() As String
            Get
                Return ResourceManager.GetString("FinishedSpanish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to divANS Graphical User Interface.
        '''</summary>
        Friend ReadOnly Property FormName() As String
            Get
                Return ResourceManager.GetString("FormName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Interfáz Gráfica para divANS.
        '''</summary>
        Friend ReadOnly Property FormNameSpanish() As String
            Get
                Return ResourceManager.GetString("FormNameSpanish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start!.
        '''</summary>
        Friend ReadOnly Property StartButton() As String
            Get
                Return ResourceManager.GetString("StartButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¡Comenzar!.
        '''</summary>
        Friend ReadOnly Property StartButtonSpanish() As String
            Get
                Return ResourceManager.GetString("StartButtonSpanish", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
